- name: Create Security Groups
  hosts: localhost
  gather_facts: true
  collections:
    - openstack.cloud
  vars:
    security_groups:
      - name: internet_access
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0
      - name: couchdb_access
        description: "Security group for CouchDB default access"
        protocol: tcp
        port_range_min: 5984
        port_range_max: 5984
        remote_ip_prefix: 0.0.0.0/0
      - name: ssh_access
        description: "Security group for ssh access"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
      - name: couchdb_clusteraccess
        description: "Security group for couchdb cluster access"
        protocol: tcp
        port_range_min: 9100
        port_range_max: 9200
        remote_ip_prefix: 0.0.0.0/0
      - name: couchdb_clusteraccess2
        protocol: tcp
        port_range_min: 4369
        port_range_max: 4369
        remote_ip_prefix: 0.0.0.0/0
      - name: couchdb_clusteraccess3
        protocol: tcp
        port_range_min: 5986
        port_range_max: 5986
        remote_ip_prefix: 0.0.0.0/0
      - name: frontend_portaccess
        protocol: tcp
        port_range_min: 8080
        port_range_max: 8080
        remote_ip_prefix: 0.0.0.0/0
   tasks:
   - name: Create a security group
     openstack.cloud.security_group:
       name: " {{ item.name }}"
       description: " {{ item. description }}"
       state: present
       security_group_rules:
         - ether_type: IPv6
           protocol: any
           direction: egress
           port_range_min: 1
           port_range_max: 65535
           remote_ip_prefix: ::/0
         - ether_type: IPv4
           protocol: any
           direction: egress
           port_range_min: 1
           port_range_max: 65535
           remote_ip_prefix: 0.0.0.0/0
         - ether_type: IPv6
           protocol: any
           direction: ingress
           port_range_min: 1
           port_range_max: 65535
           remote_ip_prefix: ::/0
         - ether_type: IPv4
           protocol: any
           direction: ingress
           port_range_min: 1
           port_range_max: 65535
           remote_ip_prefix: 0.0.0.0/0
       loop: "{{ security_groups }}"
    - name: Create security group rules
      openstack.cloud.security_group_rule:
        security_group: "{{ item.name }}"
        protocol: "{{ item.protocol }}"
        port_range_min: "{{ item.port_range_min }}"
        port_range_max: "{{ item.port_range_max }}"
        remote_ip_prefix: "{{ item.remote_ip_prefix }}"
        state: present
      loop: "{{ security_groups }}"
     



