- name: Deploy CouchDB Databases
  hosts: mastodonmaster
  remote_user: ubuntu
  vars:
    user: admin
    admin_password: admin
  become: true
  tasks:
    - name: Create Twitter SA3 Database
      uri:
        url: "http://{{ user }}:{{ admin_password }}@{{ inventory_hostname }}:5984/twittersa3"
        method: PUT
        return_content: yes
        status_code: 201
        force_basic_auth: yes
    - name: Create Mastadon Database
      uri:
        url: "http://{{ user }}:{{ admin_password }}@{{ inventory_hostname }}:5984/mastadon"
        method: PUT
        return_content: yes
        status_code: 201
        force_basic_auth: yes
    - name: Create mental health subtopics
      set_fact:
        subtopics: ['mentalhealth', 'depression', 'anxiety', 'health', 'mentalhealthawareness']
    - name: Create mental health databases
      uri:
        url: "http://{{ user }}:{{ admin_password }}@{{ inventory_hostname }}:5984/{{ item }}"
        method: PUT
        return_content: yes
        status_code: 201
        force_basic_auth: yes
      loop: "{{ subtopics }}"



    

   
 
     

