- name: Create Volume
  hosts: localhost
  gather_facts: true
  collections:
    - openstack.cloud
  vars:
    availability_zone: melbourne-qh2-uom
    volumes:
      - vol_name: data@twitternode1
        vol_size: 100
      - vol_name: data@twitternode2
        vol_size: 100
  tasks:
  - name: Create volume(s) on NecTAR
    openstack.cloud.volume:
      display_name: "{{ item.vol_name }}"
      size: "{{ item.vol_size }}"
      availability_zone: "{{ availability_zone }}"
      wait: true
      timeout: 600
      state: present
    loop: "{{ volumes }}"
    register: os_val
 


