- name: Setup Mastadon database views
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_dir: "{{playbook_dir}}"
    venv_path: "{{ project_dir }}/mastadon_script/venv/"
    couchdb_ip: 172.26.135.89
  tasks:
    - name: Create mental health subtopics
      set_fact:
        subtopics: ['mentalhealth', 'depression', 'anxiety', 'health', 'mentalhealthawareness']
    - name: Install virtualenv using pip
      pip:
        name: virtualenv
        executable: pip3
        state: present
    - name: Create virtual environment
      command: /usr/bin/python3 -m venv {{ venv_path }}
    - name: Install required packages in virtual environment
      become: true
      script: "{{ project_dir }}/mastadon_script/requirementsinstall.sh"
      args:
        chdir: "{{ project_dir }}/mastadon_script"

    - name: Create Index View in all mentalhealth subtopic database
      become: true
      script: "{{ project_dir }}/mastadon_script/initialise_view.sh {{ couchdb_ip }} {{ item }}"
      args:
        chdir: "{{ project_dir }}/mastadon_script"
      loop: "{{ subtopics }}"
    - name: Create tag count view in Mastadon database
      become: true
      script: "{{ project_dir }}/mastadon_script/general_iniview.sh {{ couchdb_ip }}"
      args:
        chdir: "{{ project_dir }}/mastadon_script"
